name: Publish Package to npmjs
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        name: Install pnpm

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: '.node-version'

      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        id: release
        with:
          release-type: node

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - run: pnpm build
        if: ${{ steps.release.outputs.release_created }}

      - run: pnpm publish --access public --no-git-checks
        if: ${{ steps.release.outputs.release_created }}
