name: Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - run: pnpm install --frozen-lockfile
      - run: pnpm test